version: "3.8"
services:
  db:
    image: postgis/postgis:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "${DB_DATABASE}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USERNAME}"
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql
  cache:
    image: redis:6.0.9-alpine
  app:
    depends_on:
      - db
      - cache
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
    volumes:
      - .:/var/www
      - ${HOME}/.composer:/.composer


  nginx:
    depends_on:
      - app
    image: nginx:alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - .:/var/www
      - ./nginx:/etc/nginx/conf.d/

volumes:
  pgdata:
    driver: local
